# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChatAiDemo' do
  
  # use_frameworks!
  
  pod 'SnapKit', '~> 5.6.0'
  pod 'Moya', '~> 15.0.0'
  pod 'HandyJSON', '~> 5.0.4-beta'

end
