# source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChatAiDemo' do
  
  # use_frameworks!
  # 网络
  pod 'Moya', '~> 15.0.0'
  # 约束
  pod 'SnapKit', '~> 5.6.0'
  # JSON解析
  pod 'HandyJSON', '~> 5.0.4-beta'
  # 下拉刷新
  pod 'MZRefresh', '~> 0.0.6'

end
